<?php
return [
    'font_awesome' => [
        ['class' => 'fas fa-info-circle',     'label' => 'Informasi'],
        ['class' => 'fas fa-check-circle',    'label' => 'Ceklis'],
        ['class' => 'fas fa-times-circle',    'label' => 'Tolak/Salah'],
        ['class' => 'fas fa-question-circle', 'label' => 'Bantuan'],
        ['class' => 'fas fa-award',           'label' => 'Penghargaan'],
        ['class' => 'fas fa-certificate',     'label' => 'Sertifikat'],
        ['class' => 'fas fa-star',            'label' => 'Bintang/Ulasan'],
        ['class' => 'fas fa-tags',            'label' => 'Diskon/Label'],
        ['class' => 'fas fa-unlock',          'label' => 'Akses Terbuka'],
        ['class' => 'fas fa-file-alt',        'label' => 'Dokumen'],
        ['class' => 'fas fa-book-open',       'label' => 'Buku Terbuka'],
        ['class' => 'fas fa-archive',         'label' => 'Arsip'],
        ['class' => 'fas fa-newspaper',       'label' => 'Jurnal/Berita'],
        ['class' => 'fas fa-download',        'label' => 'Unduh'],
        ['class' => 'fas fa-upload',          'label' => 'Unggah'],
        ['class' => 'fas fa-rocket',          'label' => 'Publikasi Cepat'],
        ['class' => 'fas fa-microscope',      'label' => 'Riset'],
        ['class' => 'fas fa-flask',           'label' => 'Penelitian'],
        ['class' => 'fas fa-atom',            'label' => 'Sains'],
        ['class' => 'fas fa-laptop-code',     'label' => 'Teknologi'],
        ['class' => 'fas fa-cogs',            'label' => 'Pengaturan'],
        ['class' => 'fas fa-database',        'label' => 'Data'],
        ['class' => 'fas fa-users',           'label' => 'Pengguna'],
        ['class' => 'fas fa-user-friends',    'label' => 'Komunitas'],
        ['class' => 'fas fa-comments',        'label' => 'Diskusi'],
        ['class' => 'fas fa-bullhorn',        'label' => 'Pengumuman'],
        ['class' => 'fas fa-headset',         'label' => 'Dukungan'],
        ['class' => 'fas fa-language',        'label' => 'Bilingual'],
        ['class' => 'fas fa-concierge-bell',  'label' => 'Layanan'],
        ['class' => 'fas fa-bullseye',        'label' => 'Tujuan'],
        ['class' => 'fas fa-video',           'label' => 'Video/Daring'],
    ]
];